name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: >-
          --entrypoint=""
          -e SERVICES=s3
          -e DEFAULT_REGION=us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Wait for Localstack to be ready
      run: |
        until curl -s http://localhost:4566/health | grep "\"s3\": \"running\""; do
          echo "Waiting for Localstack to be ready..."
          sleep 5
        done

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: "mock_access_key"
        AWS_SECRET_ACCESS_KEY: "mock_secret_key"
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_ENDPOINT_URL: "http://localhost:4566"
